### ISSUE TITLE
Rename to ngx-intersection

### ISSUE THREAD

**Issue by mralexandernickel** [mralexandernickel/ngx-intersection#14]

**Comment by k3nsei** [comment]
This is reserved name on github and npm.
https://github.com/ngx-intersection/ngx-intersection
https://www.npmjs.com/package/@ngx-intersection/core

This will be new name of https://github.com/k3nsei/ng-in-viewport

So please stop using it. Btw. there is no need for another library which is doing the same thing. You can start contributing to mine.
